kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: db_cicd_api
  namespace: apic_cicd
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./db_cicd_api-spec.yml
  policy-sequence:
    - $ref: apic_cicd:db_cicd_seq:1.0
