kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: Quota-ynicfe
  namespace: apic_cicd
  version: '1.0'
  tags: []
  description: ''
spec:
  maxRequest: 3
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        intervalOffset: -1
