openapi: 3.0.1
info:
  title: db_cicd_api
  version: '1.0'
servers:
  - url: /db/cicd
paths:
  /:
    summary: ''
    description: ''
    get:
      responses:
        '200':
          description: 200 ok
